import { 基本图元 } from './图元';
export * from './文本';
import 线 from './线';
import 椭圆 from './椭圆';
import 点 from './点';
import 填充区域 from './填充区域';
import 箭头 from './箭头';
import 单元格 from './单元格';
import 时钟 from './时钟';
export { 基本图元, 线, 椭圆, 点, 填充区域, 箭头, 单元格, 时钟 };
