import vue from '@vitejs/plugin-vue';
import { ConfigEnv, UserConfig, defineConfig } from 'vite';

const path = require('path');

function pathResolve(dir: string) {
  return path.resolve(process.cwd(), '.', dir);
}
/**
 * @type {import('vite').UserConfig}
 */
module.exports = defineConfig(({ command, mode }: ConfigEnv): UserConfig => {
  return {
    plugins: [vue()], // to process SFC
    resolve: {
      alias: [
        {
          find: /@\//,
          replacement: pathResolve('src') + '/',
        },
      ],
    },
    build: {
      sourcemap: true,
      lib: {
        entry: path.resolve(__dirname, 'src/index.ts'),
        name: 'yakies-components',
        formats: ['es'], // adding 'umd' requires globals set to every external module
        fileName: (format) => `aea-components.${format}.js`,
      },
      rollupOptions: {
        // external modules won't be bundled into your library
        external: ['vue','ant-design-vue', 'pinia'], // not every external has a global
        output: {
          // disable warning on src/index.ts using both default and named export
          exports: 'named',
          // Provide global variables to use in the UMD build
          // for externalized deps (not useful if 'umd' is not in lib.formats)
          globals: {
            vue: 'Vue',
          },
        },
      },
      emptyOutDir: false, // to retain the types folder generated by tsc
    },
  }
});
